export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CREATE_SUCCESS = 'AUTH_CREATE_SUCCESS';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
