export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CREATE_SUCCESS = 'AUTH_CREATE_SUCCESS';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

export const FAVORITES_START = 'FAVORITES_START';
export const FAVORITES_FAIL = 'FAVORITES_FAIL';
export const FAVORITES_SUCCESS = 'FAVORITES_SUCCESS';
